version: '3'
services:
  nginx:ls
    container_name: local-nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  app:
    restart: always
    build: .
    working_dir: /app
    volumes:
      - .:/app
    expose:
      - "8080"
    command: mvn clean spring-boot:run